### ISSUE TITLE
[Bug] Update System error

### ISSUE THREAD

**Issue by mscreations** [qmk/qmk_distro_wsl#66]
### Describe the Bug

QMK WSL Version 0.4.1
Version ID: 4a26b839392a1f3e5d9751aa06434e173026aa89

When performing "Update System" from qmk-admin, get an error exception because it can't find pip in `/usr/bin`. pip is installed in `/usr/local/bin`.

It also appears that pip is not automatically updated as I manually had to run `pip install --upgrade pip`

Resolution:
`sudo ln -s /usr/local/bin/pip /usr/bin/pip`

**Comment by tzarc** [comment]
More context:

```
[qmk@nickb-desktop qmk_firmware]$ python3 -m pip install -r requirements-dev.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: appdirs in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 2)) (1.4.4)
Requirement already satisfied: argcomplete in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 3)) (2.0.0)
Requirement already satisfied: colorama in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 4)) (0.4.5)
Requirement already satisfied: dotty-dict in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 5)) (1.3.1)
Requirement already satisfied: hid in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 6)) (1.0.5)
Requirement already satisfied: hjson in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 7)) (3.1.0)
Requirement already satisfied: jsonschema>=4 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 8)) (4.13.0)
Requirement already satisfied: milc>=1.4.2 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 9)) (1.6.6)
Requirement already satisfied: pygments in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 10)) (2.13.0)
Requirement already satisfied: pyserial in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 11)) (3.5)
Requirement already satisfied: pyusb in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 12)) (1.2.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 13)) (9.2.0)
Requirement already satisfied: nose2 in /usr/local/lib/python3.9/dist-packages (from -r requirements-dev.txt (line 5)) (0.12.0)
Collecting flake8
  Downloading flake8-6.0.0-py2.py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.8/57.8 kB 16.3 MB/s eta 0:00:00
Collecting pep8-naming
  Downloading pep8_naming-0.13.3-py3-none-any.whl (8.5 kB)
Collecting pyflakes
  Downloading pyflakes-3.0.1-py2.py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 34.1 MB/s eta 0:00:00
Requirement already satisfied: yapf in /usr/local/lib/python3.9/dist-packages (from -r requirements-dev.txt (line 9)) (0.32.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.9/dist-packages (from jsonschema>=4->-r requirements.txt (line 8)) (22.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.9/dist-packages (from jsonschema>=4->-r requirements.txt (line 8)) (0.18.1)
Requirement already satisfied: spinners in /usr/local/lib/python3.9/dist-packages (from milc>=1.4.2->-r requirements.txt (line 9)) (0.0.24)
Requirement already satisfied: halo in /usr/local/lib/python3.9/dist-packages (from milc>=1.4.2->-r requirements.txt (line 9)) (0.0.31)
Collecting pycodestyle<2.11.0,>=2.10.0
  Downloading pycodestyle-2.10.0-py2.py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 kB 15.5 MB/s eta 0:00:00
Collecting mccabe<0.8.0,>=0.7.0
  Downloading mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.9/dist-packages (from halo->milc>=1.4.2->-r requirements.txt (line 9)) (1.1.0)
Requirement already satisfied: log-symbols>=0.0.14 in /usr/local/lib/python3.9/dist-packages (from halo->milc>=1.4.2->-r requirements.txt (line 9)) (0.0.14)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.9/dist-packages (from halo->milc>=1.4.2->-r requirements.txt (line 9)) (1.16.0)
Installing collected packages: pyflakes, pycodestyle, mccabe, flake8, pep8-naming
  WARNING: The script pyflakes is installed in '/home/qmk/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pycodestyle is installed in '/home/qmk/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script flake8 is installed in '/home/qmk/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed flake8-6.0.0 mccabe-0.7.0 pep8-naming-0.13.3 pycodestyle-2.10.0 pyflakes-3.0.1
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/rich/console.py", line 1673, in print
    extend(render(renderable, render_options))
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/rich/console.py", line 1305, in render
    for render_output in iter_render:
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
    for line in lines:
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/rich/segment.py", line 249, in split_lines
    for segment in segments:
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/rich/console.py", line 1283, in render
    renderable = rich_cast(renderable)
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/rich/protocol.py", line 36, in rich_cast
    renderable = cast_method()
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/self_outdated_check.py", line 130, in __rich__
    pip_cmd = get_best_invocation_for_this_pip()
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/utils/entrypoints.py", line 58, in get_best_invocation_for_this_pip
    if found_executable and os.path.samefile(
  File "/usr/lib/python3.9/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip'
Call stack:
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/pip/__main__.py", line 31, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main
    self.handle_pip_version_check(options)
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/req_command.py", line 190, in handle_pip_version_check
    pip_self_version_check(session, options)
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/self_outdated_check.py", line 236, in pip_self_version_check
    logger.warning("[present-rich] %s", upgrade_prompt)
  File "/usr/lib/python3.9/logging/__init__.py", line 1454, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.9/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 948, in handle
    self.emit(record)
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/utils/logging.py", line 179, in emit
    self.handleError(record)
Message: '[present-rich] %s'
Arguments: (UpgradePrompt(old='22.2.2', new='23.1.2'),)
```
